#!/bin/sh
# $1 = exit code, $2 = signal flag (1 = killed by signal)
# During normal shutdown s6-supervise sends SIGTERM (exit code 143).
# If the service handles SIGTERM gracefully, exit code is 0.
# If s6-supervise has to use SIGKILL, exit code is 137.
# In all these cases, do not call halt.
if test "$1" -eq 0 || test "$1" -eq 143 || test "$1" -eq 137; then
  exit 125
fi
exec /run/s6/basedir/bin/halt
