#!/command/with-contenv bash
mkdir -p "${XDG_RUNTIME_DIR}/podman"
rm -f "${XDG_RUNTIME_DIR}/podman/podman.sock"
exec /usr/bin/podman system service --time=0 "unix://${XDG_RUNTIME_DIR}/podman/podman.sock"
